# Generated by Django 4.0.4 on 2022-07-11 06:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PlanModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ResultModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.IntegerField(verbose_name='day')),
                ('where', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='MemoModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('content', models.CharField(max_length=100)),
                ('count', models.IntegerField(verbose_name='count')),
                ('plan_pk', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='route.planmodel')),
            ],
        ),
    ]
